config/routes.rb
Rails.application.routes.draw do
  resources :appwebexemps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appwebexemp.rb
class Appwebexemp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appwebexemps_controller.rb
class AppwebexempsController < ApplicationController
  before_action :set_appwebexemp, only: [:show, :edit, :update, :destroy]

  # GET /appwebexemps
  # GET /appwebexemps.json
  def index
    @appwebexemps = Appwebexemp.all
  end

  # GET /appwebexemps/1
  # GET /appwebexemps/1.json
  def show
  end

  # GET /appwebexemps/new
  def new
    @appwebexemp = Appwebexemp.new
  end

  # GET /appwebexemps/1/edit
  def edit
  end

  # POST /appwebexemps
  # POST /appwebexemps.json
  def create
    @appwebexemp = Appwebexemp.new(appwebexemp_params)

    respond_to do |format|
      if @appwebexemp.save
        format.html { redirect_to @appwebexemp, notice: 'Appwebexemp was successfully created.' }
        format.json { render :show, status: :created, location: @appwebexemp }
      else
        format.html { render :new }
        format.json { render json: @appwebexemp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appwebexemps/1
  # PATCH/PUT /appwebexemps/1.json
  def update
    respond_to do |format|
      if @appwebexemp.update(appwebexemp_params)
        format.html { redirect_to @appwebexemp, notice: 'Appwebexemp was successfully updated.' }
        format.json { render :show, status: :ok, location: @appwebexemp }
      else
        format.html { render :edit }
        format.json { render json: @appwebexemp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appwebexemps/1
  # DELETE /appwebexemps/1.json
  def destroy
    @appwebexemp.destroy
    respond_to do |format|
      format.html { redirect_to appwebexemps_url, notice: 'Appwebexemp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appwebexemp
      @appwebexemp = Appwebexemp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appwebexemp_params
      params.require(:appwebexemp).permit(:nome, :id_seq, :endereco, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appwebexemps_helper.rb
module AppwebexempsHelper
end

app/views/appwebexemps/_form.html.erb
<%= form_with(model: appwebexemp, local: true) do |form| %>
  <% if appwebexemp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appwebexemp.errors.count, "error") %> prohibited this appwebexemp from being saved:</h2>

      <ul>
      <% appwebexemp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :id_seq %>
    <%= form.text_field :id_seq %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appwebexemps/edit.html.erb
<h1>Editing Appwebexemp</h1>

<%= render 'form', appwebexemp: @appwebexemp %>

<%= link_to 'Show', @appwebexemp %> |
<%= link_to 'Back', appwebexemps_path %>

app/views/appwebexemps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appwebexemps</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Id seq</th>
      <th>Endereco</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appwebexemps.each do |appwebexemp| %>
      <tr>
        <td><%= appwebexemp.nome %></td>
        <td><%= appwebexemp.id_seq %></td>
        <td><%= appwebexemp.endereco %></td>
        <td><%= appwebexemp.email %></td>
        <td><%= link_to 'Show', appwebexemp %></td>
        <td><%= link_to 'Edit', edit_appwebexemp_path(appwebexemp) %></td>
        <td><%= link_to 'Destroy', appwebexemp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appwebexemp', new_appwebexemp_path %>

app/views/appwebexemps/new.html.erb
<h1>New Appwebexemp</h1>

<%= render 'form', appwebexemp: @appwebexemp %>

<%= link_to 'Back', appwebexemps_path %>

app/views/appwebexemps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @appwebexemp.nome %>
</p>

<p>
  <strong>Id seq:</strong>
  <%= @appwebexemp.id_seq %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @appwebexemp.endereco %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appwebexemp.email %>
</p>

<%= link_to 'Edit', edit_appwebexemp_path(@appwebexemp) %> |
<%= link_to 'Back', appwebexemps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>